# Generated by Django 4.2.4 on 2023-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='text_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='arc',
            name='background_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='arc',
            name='background_shadow',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
