# Generated by Django 4.2.3 on 2023-08-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arc_text_color_alter_arc_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arc',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='arc',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('year', models.IntegerField()),
                ('filler', models.BooleanField(default=False)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.arc')),
            ],
        ),
        migrations.AddField(
            model_name='arc',
            name='saga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.saga'),
        ),
    ]
