# Generated by Django 4.2.3 on 2023-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saga_chapter_spoiler_alter_arc_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='filler',
            field=models.BooleanField(default=False),
        ),
    ]
